return {
  -- "jackMort/ChatGPT.nvim",
  -- enabled = false,
  -- event = "VeryLazy",
  -- config = function()
  --   require("chatgpt").setup({
  --     api_key_cmd = "pass show api/tokens/openai",
  --     openai_params = {
  --       model = "gpt-4o",
  --     },
  --     openai_edit_params = {
  --       model = "gpt-4o",
  --     },
  --   })
  -- end,
  -- dependencies = {
  --   "MunifTanjim/nui.nvim",
  --   "nvim-lua/plenary.nvim",
  --   "nvim-telescope/telescope.nvim",
  -- },
}
